### ISSUE TITLE
Defining file formats

### ISSUE THREAD

**Issue by rcannood** [viash-hub/biobase#16]
## File format specifications

If a component returns a directory or data structure such as AnnData or MuData, a specification of the file format should be provided.

### Directory file format specification

```yaml
functionality:
  # ...
  arguments:
    - name: --output
      type: file
      # ...
      example: output/
      info:
        format:
          - type: directory
            contents:
              - type: file
                name: counts.csv
                description: Normalised expression values
                required: true
              - type: file
                name: size_factors.csv
                description: The size factors created by the normalisation method, if any.
                required: false
```

### AnnData file format specification

```yaml
functionality:
  # ...
  arguments:
    - name: --output
      type: file
      # ...
      example: output.h5ad
      info:
        format:
          layers:
            - type: double
              name: normalized
              description: Normalised expression values
              required: true
          obs:
            - type: double
              name: size_factors
              description: The size factors created by the normalisation method, if any.
              required: false
          uns:
            - type: string
              name: normalization_id
              description: "Which normalization was used"
              required: true
```
