### ISSUE TITLE
Eggs to lay

### ISSUE THREAD

**Issue by rcannood** [viash-hub/biobase#2]
## Source code

* Where to store the source code?
  - [x] Option 1: Source on GitHub, builds on Viash Hub
  - [ ] Option 2: Source on Viash Hub, builds on Viash Hub
  - [ ] Option 3: Source on GitHub, Builds on GitHub

* Name of the repository?
  - [ ] Base
  - [x] BioBase
  - [ ] Components
  - [ ] BioComponents
  - [ ] Something with bio in the name
  - [ ] BioPack
  - [ ] BioTools
  - [ ] BioPackage

## Structure

* Directory structure?
  - [ ] Option 1: repo name `base`, component at `src/bio/arriba`.
  - [x] Option 2: repo name `biobase`, component at `src/arriba`.
* Namespace structure?
  - [ ] Option 1: Structure components hierarchically, e.g. `src/bio/rnaseq/gene_fusion/arriba`
  - [x] Option 2: Keep the repository very flat, e.g. `base:src/bio/arriba` or `biobase:src/arriba`.
* How to structure subcommands?
  - [ ] Option 1 - Naive: `src/arriba/qc` and `src/.../arriba/run`. This will cause imported components to be called `run` instead of `arriba_run`.
  - [x] Option 2 - Repetition: `src/arriba/arriba_run`. This causes some duplication of the tool name but makes it easier to work with inside of workflows.
  - [ ] Option 3 - Flatten: `src/arriba_run`. Will also solve the problem but make the repository very flat. Might make it harder to have shared resources (e.g. test resources)

## Test resources

* Do we store a script for how test resources were generated? If possible, specify which version of Viash components were used.
  - [x] Yes
  - [ ] No
* Where to host test resources? The arriba test resources were small enough (<3KB) so I just uploaded them to the git repo. What do we do with larger test resources? S3, Zenodo, Figshare, ...?
  - [ ] Option 1: Always S3
  - [x] Option 2: In the repo if <100KB, otherwise S3
  - [ ] Option 3: Always Zenodo or Figshare
  - [ ] Option 4: In the repo if <100KB, otherwise zenodo or figshare

## Traceability

* For Arriba, I stored the output of `arriba -h` in `help.sh`. This was not only useful for me, but it might be useful in the future when we are able to automate things a bit better.
  - [x] Option 1: store the output of the help in `help.txt`. The first line should state the command.
  - [ ] Option 2: add an info field with the help command, e.g. `info: { help_command: "arriba -h" }`
  - [ ] Option 3: store the command in a script:
    ```yaml
    - type: bash_script
      usage: help
      text: arriba -h
    - type: bash_script
      usage: version
      text: |
        arriba -h | grep 'Version:' 2>&1 |  sed 's/Version:\s\(.*\)/arriba: "\1"/'
    ```
    (Though for now in comments because Viash doesn't support the `usage` field yet!)
  - [ ] Option 4: As part of the Docker setup, write it to a file e.g. `/var/help.txt`
* Tracking version numbers:
  - [ ] Option 1: Store the command for the version in `version.sh`. This currently outputs information to STDOUT in the form of a yaml.
    ```yaml
    arriba: "2.4.0"
    ```
    Note that I used quotes to ensure that whatever version output is generated is actually a string instead of a double.
  - [ ] Option 2: Same but quotes are not necessary. E.g. Output in the form of `arriba: 2.4.0` or `arriba: 2.4` are also OK.
  - [ ] Option 3: Store the command in the config, e.g. `info: { version_command: "..." }`
  - [ ] Option 4: store the command in a script:
    ```yaml
    - type: bash_script
      usage: help
      text: arriba -h
    - type: bash_script
      usage: version
      text: |
        arriba -h | grep 'Version:' 2>&1 |  sed 's/Version:\s\(.*\)/arriba: "\1"/'
    ```
  - [x] Option 5: As part of the Docker setup, write it to a file e.g. `/var/software_versions.yaml`

## Arguments

* Do we include all tool arguments? In projects like `nf-core/modules` and `snakemake/snakemake-wrappers`, modules will typically have a field which allows users to pass extra parameters to the component. However, this requires users to look up the original tool's documentation.
  - [ ] Option 1 - Pragmatic approach: only specify the parameters that are needed and extra arguments can be passed via an argument called `args` or `extra_args`.
  - [ ] Option 2 - Only add common arguments: Additional arguments need to be added with a PR.
  - [x] Option 3 - Attempt to construct an interface that makes sense, which allows us to adapt the original interface
  - [ ] Option 4 - Attempt to construct an interface that makes sense by hiding arguments that are not commonly used with `info: { hidden: true }`
  - [x] Option 5 - Include all arguments: though this is more work upfront.
* Do we rename tool arguments?
  - [x] Whenever possible, we reuse the original tool's argument names. However, arguments like `--foo-bar` need to be renamed to `--foo_bar`. Some tools also only offer short flags like `-x` so we'll need to invent useful argument names for those. Users that are actually familiar with the original tool might need to use different argument names.
* If an argument has been renamed but otherwise has a corresponding flag in the original tool, do we store this in the config?
  - [ ] Yes with documentation:
    ```yaml
    - type: file
      name: --bam
      # ...
      info:
        original_flag: -x
    ```
  - [x] Yes, when there are significant changes, whenever possible
    ```yaml
    - type: file
      name: --bam
      alternatives: [-x]
    ```
  - [ ] No

## Component metadata

* How to store component metadata? We should update our JSON schema such that we know when we haven't filled in required data.
  - [x] Proposal:
    ```yaml
    functionality:
      name: arriba
      namespace: bio
      description: Detect gene fusions from RNA-Seq data
      info:
        keywords: [Gene fusion, RNA-Seq]
        homepage: https://arriba.readthedocs.io/en/latest/
        documentation: https://arriba.readthedocs.io/en/latest/
        repository: https://github.com/suhrig/arriba
        reference: "doi:10.1101/gr.257246.119"
        licence: MIT
      requirements:
        cpus: 1
    ```
  - [ ] Proposal:
    ```yaml
    functionality:
      name: arriba
      namespace: bio
      description: Detect gene fusions from RNA-Seq data
      info:
        tools:
          arriba:
            keywords: [Gene fusion, RNA-Seq]
            homepage: https://arriba.readthedocs.io/en/latest/
            documentation: https://arriba.readthedocs.io/en/latest/
            repository: https://github.com/suhrig/arriba
            reference: "doi:10.1101/gr.257246.119"
            licence: MIT
      requirements:
        cpus: 1
    ```
  - [ ] Proposal:
    ```yaml
    functionality:
      name: arriba
      namespace: bio
      description: Detect gene fusions from RNA-Seq data
      info:
        keywords: [Gene fusion, RNA-Seq]
        wrapper:
          homepage: https://arriba.readthedocs.io/en/latest/
          documentation: https://arriba.readthedocs.io/en/latest/
          repository: https://github.com/suhrig/arriba
          reference: "doi:10.1101/gr.257246.119"
          licence: MIT
      requirements:
        cpus: 1
    ```
  - [ ] Fill in alternative proposal here

* How to store references?
  - [ ] As a `str | str[]`:
    ```yaml
    reference: [ "doi:10.1101/gr.257246.119", "<...bibtex entry...>" ]
  - [x] As a dict:
    ```yaml
    reference:
      doi: ["10.1101/gr.257246.119", "..."]
      bibtex: "..."
    ```
  - [ ] As a dict:
    ```yaml
    reference_doi: ["10.1101/gr.257246.119", "..."]
    reference_bibtex: "..."
    ```
